GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnJ5QGdtYWlsIiwiaWQiOiI2NzU0Y2MxZGQ5OTQyZDI3NDUzODg1ZjAiLCJpYXQiOjE3MzM3ODY3MDAsImV4cCI6MTczMzc4NzAwMH0.nCGIwCdKh7qH9ryWXlp6iykdEZBAQqFBXYhjCHuSzIM