PUT http://localhost:3001/api/users/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnJ5QGdtYWlsIiwiaWQiOiI2NzU0Y2MxZGQ5OTQyZDI3NDUzODg1ZjAiLCJpYXQiOjE3MzM3OTg4OTQsImV4cCI6MTczMzc5OTE5NH0.M9sRAY8DR2-nzzGsn_a1qz_UIyWoc5vaVsssMVjnANA

{
  "name": "Harry Cool"
}